server:
  port: 8010
  servlet:    encoding:      force: true
      charset: UTF-8
      enabled: true
  
spring:  datasource:
    username: root    password: root
    url: jdbc:mysql://localhost:3306/auth
    driver-class-name: com.mysql.jdbc.Driver
      
mybatis:  mapper-locations: classpath:mapping/*Mapper.xml    
  type-aliases-package: com.zbk.springboot.entity
  
  #打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
pagehelper:  
  helper-dialect:  mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql